---
title: "Day17"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(cartography)
library(osmdata)
library(sf)
library(tidyverse)
library(tmap)

tmap_mode("plot")
```

## Load Data

```{r}
# Load map boundary

mapBoundary <- read_sf(here::here("data/derived-data/mapBoundaryDay17.shp"))

mapBoundary <- mapBoundary %>% 
  st_transform(3857)

```

```{r}
# Load in previously downloaded data from OSM

bangaloreBuildings <- readRDS(here::here("data/raw-data/bangaloreBuildings.rds"))

bangaloreBuildings <- bangaloreBuildings %>%
  select(osm_id, geometry)

bangaloreBuildings <- bangaloreBuildings %>%
  st_transform(3857)

```

## Wrangle Data

```{r}
# Intersect Data

mapBuildings <- st_intersection(bangaloreBuildings, mapBoundary)

```

```{r}
# Create context

contextBoundary <- st_buffer(mapBoundary, 2000, endCapStyle = "SQUARE")

# Intersect

contextBoundary <- st_difference(contextBoundary, mapBoundary)

# Buildings in context

contextBuildings <- st_intersection(bangaloreBuildings, contextBoundary)
```


## Build Map

```{r}
# Put layers together

mapBangaloreCore <- tm_shape(mapBuildings) +
  tm_fill(col = "#000000") +
  tm_layout(bg.color = "#ffffff",
            frame = F,
            attr.outside = T,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Plan of the Siege of Bangalore by Lord Cornwallis, 1797",
            main.title.color = "#000000",
            main.title.size = 1.75,
            main.title.fontface = 2,
            main.title.fontfamily = "Arial Narrow",
            title = "Extents as seen today*",
            title.color = "#000000",
            title.size = 1,
            title.position = c("left", "TOP"),
            title.fontface = 2) + 
  tm_credits("#30DayMapChallenge | Day 17 | Anirudh Govind | Nov 2020\nMap data © OpenStreetMap contributors and available from https://www.openstreetmap.org",
             col = "#000000",
             size = 0.8,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow") +
  tm_shape(mapBoundary) +
  tm_borders(col = "#000000",
             lwd = 2) +
  tm_shape(contextBuildings) +
  tm_fill(col = "#e5e5e5")
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = mapBangaloreCore,
          filename = here::here("exports/Day17.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")
```

