---
title: "Day5"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(osmdata)
library(sf)
library(tidyverse)
library(tmap)

tmap_mode("plot")
```

## Get Data

```{r}
# Get water data from OSM

# query <- getbb("Bangalore") %>% 
#   opq() %>% 
#   add_osm_feature("natural", "water")
# 
# str(query)
# 
# osmWater <- osmdata_sf(query)
# 
# bangaloreWater <- osmWater$osm_polygons
# 
# saveRDS(bangaloreWater, here::here("data/raw-data/bangaloreWater.rds"))

bangaloreWater <- readRDS(here::here("data/raw-data/bangaloreWater.rds"))

bangaloreWater <- bangaloreWater %>% 
  st_transform(3857)
```

```{r}
# Load Bangalore wards

bangaloreWardBoundary <- read_sf(here::here("data/raw-data/bangaloreWardBoundary.shp"))

bangaloreWardBoundary <- bangaloreWardBoundary%>% 
  st_transform(3857)
```

```{r}
# Load roads data (previously saved from OSM and cleaned up)

bangaloreRoads <- readRDS(here::here("data/derived-data/bangaloreRoads.rds"))
```

```{r}
# Load unclipped roads data (previously saved from OSM)

trunkRoads <- readRDS(here::here("data/raw-data/roadsTrunk.rds"))

motorRoads <- readRDS(here::here("data/raw-data/roadsMotorway.rds"))

primaryRoads <- readRDS(here::here("data/raw-data/roadsPrimary.rds"))

secondaryRoads <- readRDS(here::here("data/raw-data/roadsSecondary.rds"))
```

## Wrangle Data

```{r}
# Filter roads data to keep a smaller subset

bangaloreRoadsFilter <- bangaloreRoads %>% 
  filter(highway == "trunk" | 
           highway == "motorway" | 
           highway == "primary" | 
           highway == "secondary")

```

```{r}

# Keep only relevant data

bangaloreWater <- bangaloreWater %>% 
  select(osm_id, name, geometry)

# Calculate area of all natural waters

bangaloreWater %>% 
  mutate(area = st_area(.)) %>% 
  mutate(area = as.numeric(area)) %>% 
  mutate(totalArea = sum(area)) %>% 
  mutate(totalArea = round(totalArea, 2))

# Total area = 39848847 Sqm

# Calculate ara of natural waters within municipal boundary

bangaloreWater %>% 
  st_intersection(., bangaloreWardBoundary) %>% 
  mutate(area = st_area(.)) %>% 
  mutate(area = as.numeric(area)) %>% 
  mutate(totalArea = sum(area)) %>% 
  mutate(totalArea = round(totalArea, 2))

# Total area within municipal boundary = 21425261 Sqm
```


## Build Map

```{r}

# Define palette

palette <- c("#caf0f8",
             "#90e0ef",
             "#00b4d8",
             "#0077b6",
             "#03045e")

# Put the map together

bangaloresNaturalWatersMap <- tm_shape(bangaloreWater) +
  tm_fill(col = "#00b4d8") +
  tm_shape(bangaloreWardBoundary) +
  tm_borders(col = "#E5E5E5",
             lwd = 3,
             alpha = 0.8) +
  tm_shape(trunkRoads) +
  tm_lines(col = "#E5E5E5",
           alpha = 0.6) +
  tm_shape(motorRoads) +
  tm_lines(col = "#E5E5E5",
           alpha = 0.6) +
  tm_shape(primaryRoads) +
  tm_lines(col = "#E5E5E5",
           alpha = 0.6) +
  tm_shape(secondaryRoads) +
  tm_lines(col = "#E5E5E5",
           alpha = 0.6) +
  tm_layout(bg.color = "#ffffff",
            frame = F,
            attr.outside = T,
            inner.margins = 0,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Bangalore's Natural Waters",
            main.title.color = "#00b4d8",
            main.title.size = 1.70,
            main.title.fontface = 2,
            main.title.fontfamily = "Arial Narrow",
            title = "          39.84km² = Area of natural waters\n          21.42km² = Area of natural waters in admin boundary",
            title.color = "#00b4d8",
            title.size = 0.8,
            title.position = c("right", "bottom"),
            legend.show = F) + 
  tm_credits("#30DayMapChallenge | Day 5 | Anirudh Govind | Nov 2020\nMap data © OpenStreetMap contributors and available from https://www.openstreetmap.org",
             col = "#00b4d8",
             size = 0.8,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = bangaloresNaturalWatersMap,
          filename = here::here("exports/Day5.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")
```

