---
title: "Day19"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cartography)
library(extrafont)
# font_import()
loadfonts(device = "win")

library(osmdata)
library(raster)
library(sf)
library(tidyverse)
library(tmap)

tmap_mode("plot")
```

## Load Data

```{r}
# Load Bangalore ward boundary

bangaloreWardBoundary <- read_sf(here::here("data/raw-data/bangaloreWardBoundary.shp"))

bangaloreWardBoundary <- bangaloreWardBoundary%>% 
  st_transform(3857)

```

```{r}
# Load Bangalore wards

bangaloreWards <- read_sf(here::here("data/raw-data/bangaloreWardsUTM.shp"))

bangaloreWards <- bangaloreWards %>% 
  st_transform(3857)
```

```{r}
# Load Bangalore Population

bangalorePopulation <- raster(here::here("data/raw-data/ind_ppp_2020_UNadj_constrained.tif"))

```

## Wrangle Data

```{r}
# Transform/ Make CRS consistent

bangaloreWardBoundary <- st_transform(bangaloreWardBoundary, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

# Clip data

bangalorePopulationCrop <- crop(bangalorePopulation, bangaloreWardBoundary)

bangalorePopulationMask <- mask(bangalorePopulationCrop, bangaloreWardBoundary)

mean(bangalorePopulationMask$ind_ppp_2020_UNadj_constrained)

```

## Build Map

```{r}

# Define palette

myPalette <- c("#053061",
               "#2166ac",
               "#4393c3",
               "#92c5de",
               "#d1e5f0",
               "#fddbc7",
               "#f4a582",
               "#d6604d",
               "#b2182b",
               "#67001f")

# Put layers together

bangalorePopulationMap <- tm_shape(bangaloreWardBoundary) +
  tm_borders(col = "#000000",
             lwd = 3) + 
  tm_shape(bangalorePopulationMask) +
  tm_raster(palette = myPalette,
            colorNA = "#ffffff",
            colorNULL = "#ffffff",
            breaks = c(1,60,120,180,240,300,360,420,480,540,600),
            midpoint = 180,
            title = "Population Counts",
            style = "cont",
            showNA = T) +
  tm_shape(bangaloreWards) +
  tm_borders(col = "#000000",
             lwd = 1.5) +
  tm_layout(bg.color = "#ffffff",
            frame = F,
            attr.outside = T,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Bangalore's Estimated Population",
            main.title.color = "#000000",
            main.title.size = 1.75,
            main.title.fontface = 2,
            main.title.fontfamily = "Arial Narrow",
            title = "Blues indicate missing or unlikely data",
            title.color = "#000000",
            title.size = 1,
            title.position = c("left", "TOP"),
            title.fontface = 2) + 
  tm_credits("#30DayMapChallenge | Day 19 | Anirudh Govind | Nov 2020 | Total Population of Bangalore = 11,539,210 (?)\nBondarenko M., Kerr D., Sorichetta A., and Tatem, A.J. 2020. Census/projection-disaggregated gridded population datasets, adjusted to match the corresponding UNPD 2020 estimates,\nfor 183 countries in 2020 using Built-Settlement Growth Model (BSGM) outputs. WorldPop, University of Southampton, UK. doi:10.5258/SOTON/WP00685",
             col = "#000000",
             size = 0.8,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

## Export Map

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = bangalorePopulationMap,
          filename = here::here("exports/Day19.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")
```
