---
title: "Day10"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(exactextractr)
library(osmdata)
library(sf)
library(terra)
library(tidyverse)
library(tmap)

tmap_mode("plot")
```

## Get Data

```{r}
# Load buildings previously saved from OSM

bruBuildings <- readRDS(here::here("2021/data/rawData/bruBuildings.rds")) %>% 
  select(osm_id, 
         geometry) %>% 
  st_transform(3857)
```

```{r}
# Load in population data saved from WorlPop: https://www.worldpop.org/geodata/summary?id=49938 and convert it to an sf object

belPop <- rast(here::here("2021/data/rawData/bel_ppp_2020_UNadj_constrained.tif"))

```

## Wrangle Data

```{r}
# Now, I want a minimum bounding box

bruBound <- bruBuildings %>% 
  st_bbox() %>% 
  st_as_sfc()

mapBound <- bruBound %>% 
  st_centroid() %>% 
  st_buffer(7000)

mapLimit <- bruBound %>% 
  st_centroid() %>% 
  st_buffer(7500)
```

```{r}
bruBuildings <- bruBuildings %>% 
  st_intersection(mapBound)
```

```{r}
# Extract population for this area

belPop <- exact_extract(belPop, bruBuildings, 'sum', progress = F)
```

```{r}
# Add population back to buildings

bruBuildings$population <- belPop
```

```{r}
# See the spread of the population

bruBuildings %>% 
ggplot(aes(x = population)) +
  geom_histogram() +
  xlim(0,35)
```

## Build Map

```{r}
# Build the base layer

vizBase <- tm_shape(mapLimit) +
  tm_fill(col = "#f1eee9") +
  tm_shape(mapBound) +
  tm_fill(col = "#f1eee9") +
  tm_layout(bg.color = "#f1eee9",
            frame = F,
            frame.lwd = NA,
            attr.outside = F,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Population Distribution*",
            main.title.color = "#000000",
            main.title.size = 1.75,
            main.title.fontfamily = "Arial Narrow",
            main.title.fontface = 2,
            main.title.position = "center",
            title = "Brussels Capital Region",
            title.color = "#000000",
            title.size = 1,
            title.position = c("center", "TOP"),
            title.fontface = 2,
            legend.position = c("right", "top"),
            legend.title.color = "#f1eee9") + 
  tm_credits("#30DayMapChallenge | Day 10 | Anirudh Govind | Nov 2021 | Map data © OpenStreetMap contributors and available from https://www.openstreetmap.org\nBondarenko M., Kerr D., Sorichetta A., and Tatem, A.J. 2020. Census/projection-disaggregated gridded population datasets, adjusted to match the corresponding UNPD 2020 estimates,\nfor 183 countries in 2020 using Built-Settlement Growth Model (BSGM) outputs. WorldPop, University of Southampton, UK. doi:10.5258/SOTON/WP00685",
             col = "#000000",
             size = 1,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

```{r}
# Build the population layer

myPalette <- "Greys"

vizPop <- tm_shape(bruBuildings) +
  tm_fill(col = "population",
          palette = myPalette,
          legend.show = T,
          breaks = c(0,
                     7,
                     14,
                     21,
                     28,
                     35)) +
  tm_borders(col = "#000000",
             lwd = 0.1)
```

```{r}
# Combine layers

viz <- vizBase + 
  vizPop
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = viz,
          filename = here::here("2021/exports/Day10.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")

```

