---
title: "Day16"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(osmdata)
library(sf)
library(sfnetworks)
library(terra)
library(tidygraph)
library(tidyverse)
library(tmap)

tmap_mode("view")
```

## Get Data

```{r}
# Get highway data from OSM

query <- getbb("Leuven, Belgium") %>% 
   opq() %>% 
   add_osm_feature("highway") %>% 
   osmdata_sf()

leuHighways <- query$osm_lines

```

## Wrangle Data

```{r}
# Clean data

leuHighways <- leuHighways %>% 
  select(osm_id, highway, geometry) %>% 
  st_transform(3857)

```

```{r}
# Now, I want a minimum bounding box

leuBound <- leuHighways %>% 
  st_bbox() %>% 
  st_as_sfc()

mapBound <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(6000)

mapLimit <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(6500)

```

```{r}
# Clip the data

leuHighwaysFilter <- leuHighways %>% 
  st_intersection(mapBound)

```

```{r}
# Convert this to line strings so that I can use them with the sfnetworks package

leuHighwaysLS <- leuHighwaysFilter %>% 
  st_cast("LINESTRING")

leuHighwaysNet <- as_sfnetwork(leuHighwaysLS)

```

```{r}
# Extract nodes and edges for plotting

leuVizNodes <- leuHighwaysNet %>% 
  activate("nodes") %>% 
  st_as_sf()

leuVizEdges <- leuHighwaysNet %>% 
  activate("edges") %>% 
  st_as_sf() %>% 
  mutate(weight = as.numeric(weight))
```

```{r}
# Calculate density counts and create a grid

vizGrid <- mapBound %>% 
  st_make_grid(n = c(10,10)) %>% 
  st_as_sf() %>% 
  mutate(gridID = row_number())

leuGridPoints <- st_join(leuVizNodes, vizGrid) %>% 
  st_set_geometry(NULL)

leuGridPoints <- leuGridPoints %>% 
  left_join(.,
            vizGrid,
            by = c("gridID" = "gridID")) %>% 
  st_as_sf() %>% 
  group_by(gridID) %>% 
  summarise(density = n()) %>% 
  ungroup()

```


## Build Map

```{r}
# Build the base layer

vizBase <- tm_shape(mapLimit) +
  tm_fill(col = "#f1eee9") +
  tm_shape(mapBound) +
  tm_fill(col = "#f1eee9") +
  tm_layout(bg.color = "#f1eee9",
            frame = F,
            frame.lwd = NA,
            attr.outside = F,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Intersection Density",
            main.title.color = "#000000",
            main.title.size = 1.75,
            main.title.fontfamily = "Arial Narrow",
            main.title.fontface = 2,
            main.title.position = "center",
            title = "Leuven",
            title.color = "#000000",
            title.size = 1.25,
            title.position = c("center", "TOP"),
            title.fontface = 2,
            legend.position = c("right", "top"),
            legend.title.color = "#f1eee9") + 
  tm_credits("#30DayMapChallenge | Day 16 | Anirudh Govind | Nov 2021 | Map data © OpenStreetMap contributors and available from https://www.openstreetmap.org",
             col = "#000000",
             size = 1,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

```{r}
# Build the roads layers

myPalette = "Purples"

vizRoads <- tm_shape(leuVizNodes) +
  tm_dots(
    size = 0.03,
    alpha = 0.15,
    col = "#000000",
    palette = myPalette,
    legend.show = F,
    legend.size.show = F) +
  tm_shape(leuVizEdges) +
  tm_lines(
    col = "#000000",
    lwd = "weight",
    legend.col.show = F,
    legend.lwd.show = F) +
  tm_shape(vizGrid) +
  tm_borders(col = "#000000",
             lwd = 0.05) + 
  tm_shape(leuGridPoints) +
  # tm_fill(col = "density",
  #         palette = myPalette,
  #         alpha = 0.5) +
  tm_text(text = "density",
          col = "#ffffff",
          xmod = -1.1,
          ymod = 1.1,
          bg.color = "#000000",
          bg.alpha = 0.5)
```

```{r}
# Combine layers

viz <- vizBase + 
  vizRoads
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = viz,
          filename = here::here("2021/exports/Day16.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")

```

