---
title: "Day13"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(exactextractr)
library(osmdata)
library(sf)
library(terra)
library(tidyverse)
library(tmap)

tmap_mode("view")
```

## Get Data

```{r}
# Get building data from OSM

query <- getbb("Leuven, Belgium") %>% 
   opq() %>% 
   add_osm_feature("highway") %>% 
   osmdata_sf()

leuHighways <- query$osm_lines

```

```{r}
# Load highway data from natural earth

neHighways <- read_sf(here::here("2021/data/rawData/ne_10m_roads.shp")) %>% 
  st_transform(3857)
```

```{r}
# Load list of populated places

nePlaces <- read_sf(here::here("2021/data/rawData/ne_10m_populated_places.shp")) %>% 
  st_transform(3857)
```

```{r}
# Load list of populated places

neUrban <- read_sf(here::here("2021/data/rawData/ne_10m_urban_areas.shp")) %>% 
  st_transform(3857)
```

## Wrangle Data

```{r}
# Clean data

leuHighways <- leuHighways %>% 
  select(osm_id, geometry) %>% 
  st_transform(3857)

```

```{r}
# Now, I want a minimum bounding box

leuBound <- leuHighways %>% 
  st_bbox() %>% 
  st_as_sfc()

mapBound <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(6000)

mapLimit <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(6500)

```

```{r}
# Clip the data

leuHighwaysFilter <- leuHighways %>% 
  st_intersection(mapBound)

leuNEHighwaysFilter <- neHighways %>% 
  st_intersection(mapBound)

leuNEPlaces <- nePlaces %>% 
  st_intersection(mapBound)

leuNEBuiltUp <- neUrban %>% 
  st_intersection(mapBound)
```

## Build Map

```{r}
# Build the base layer

vizBase <- tm_shape(mapLimit) +
  tm_fill(col = "#f1eee9") +
  tm_shape(mapBound) +
  tm_fill(col = "#f1eee9") +
  tm_layout(bg.color = "#f1eee9",
            frame = F,
            frame.lwd = NA,
            attr.outside = F,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "NE Roads vs. OSM Roads",
            main.title.color = "#000000",
            main.title.size = 1.75,
            main.title.fontfamily = "Arial Narrow",
            main.title.fontface = 2,
            main.title.position = "center",
            title = "Leuven",
            title.color = "#000000",
            title.size = 1.25,
            title.position = c("center", "TOP"),
            title.fontface = 2,
            legend.position = c("right", "top"),
            legend.title.color = "#f1eee9") + 
  tm_credits("#30DayMapChallenge | Day 13 | Anirudh Govind | Nov 2021 | Map data © OpenStreetMap contributors and available from https://www.openstreetmap.org\nMade with Natural Earth. Free vector and raster map data @ naturalearthdata.com.",
             col = "#000000",
             size = 1,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

```{r}
# Build the roads layers

vizRoads <- tm_shape(leuHighwaysFilter) +
  tm_lines(col = "#000000",
           lwd = 0.1) +
  tm_shape(leuNEHighwaysFilter) +
  tm_lines(col = "#fc9272",
           lwd = 1.2)

```

```{r}
# Combine layers

viz <- vizBase + 
  vizRoads
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = viz,
          filename = here::here("2021/exports/Day13.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")

```

