---
title: "Day27"
author: "Anirudh Govind"
date: '(`r format(Sys.Date(), "%d %B, %Y")`)'
output:
  github_document:
    keep_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(extrafont)
# font_import()
loadfonts(device = "win")

library(osmdata)
library(oldtmaptools)
library(sf)
library(tidyverse)
library(tmap)
library(wesanderson)

tmap_mode("view")
```

## Get Data

```{r}
# Get highway data from OSM

queryH <- getbb("Leuven, Belgium") %>% 
   opq() %>% 
   add_osm_feature("highway") %>% 
   osmdata_sf()

leuHighways <- queryH$osm_lines

```

```{r}
# Get waste bin data from OSM

queryWB <- getbb("Leuven, Belgium") %>% 
   opq() %>% 
   add_osm_feature("amenity", "waste_basket") %>% 
   osmdata_sf()

leuWasteBasket <- queryWB$osm_points

```

## Wrangle Data

```{r}
# Clean data

leuHighways <- leuHighways %>% 
  select(osm_id, geometry) %>% 
  st_transform(3857)

leuWasteBasket <- leuWasteBasket %>% 
  select(osm_id, geometry) %>% 
  st_transform(3857)

```

```{r}
# Now, I want a minimum bounding box

leuBound <- leuHighways %>% 
  st_bbox() %>% 
  st_as_sfc()

mapBound <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(4000)

mapLimit <- leuBound %>% 
  st_centroid() %>% 
  st_buffer(4500)

```

```{r}
# Clip data to this area

leuHighwaysFilter <- leuHighways %>% 
  st_intersection(mapBound)

leuWasteBasketFilter <- leuWasteBasket %>% 
  st_intersection(mapBound)

```

```{r}
# Create a grid

leuGrid <- mapBound %>% 
  st_make_grid(cellsize = 100,
               square = T) %>% 
  st_as_sf() %>% 
  st_intersection(mapBound) %>% 
  mutate(gridID = row_number())

leuGridSP <- as(leuGrid, "Spatial")
```

```{r}
# Join the data to the grid

leuWasteBasketGrid <- st_join(leuGrid, leuWasteBasket) %>% 
  st_set_geometry(NULL)

# Summarize data

leuWasteBasketGrid <- leuWasteBasketGrid %>% 
  mutate(count = case_when(is.na(osm_id) == T ~ 0,
                           is.na(osm_id) != T ~ 1)) %>% 
  group_by(gridID) %>% 
  summarise(countSum = sum(count)) %>% 
  ungroup()

min(leuWasteBasketGrid$countSum)

max(leuWasteBasketGrid$countSum)

median(leuWasteBasketGrid$countSum)

mean(leuWasteBasketGrid$countSum)

# Join geometry again

leuWasteBasketGrid <- leuWasteBasketGrid %>% 
  left_join(.,
            leuGrid,
            by = c("gridID" = "gridID")) %>% 
  st_as_sf()

# Calculate densities

leuWBDensities <- smooth_map(leuWasteBasketGrid,
                             var = "countSum")
```

## Build Map

```{r}
# Build the base layer

vizBase <- tm_shape(mapLimit) +
  tm_fill(col = "#000000") +
  tm_shape(mapBound) +
  tm_fill(col = "#252525") +
  tm_borders(col = "#f1eee9",
             lwd = 1) +
  tm_layout(bg.color = "#000000",
            frame = F,
            frame.lwd = NA,
            attr.outside = F,
            outer.margins = 0,
            asp = 0,
            scale = 0.8,
            main.title = "Waste Baskets",
            main.title.color = "#f1eee9",
            main.title.size = 1.75,
            main.title.fontfamily = "Arial Narrow",
            main.title.fontface = 2,
            main.title.position = "center",
            title = "Leuven",
            title.color = "#f1eee9",
            title.size = 1.25,
            title.position = c("center", "TOP"),
            title.fontface = 2,
            legend.position = c("right", "bottom"),
            legend.title.color = "#000000",
            legend.text.color = "#f1eee9",
            legend.height = -0.1) + 
  tm_credits("#30DayMapChallenge | Day 27 | Anirudh Govind | Nov 2021\nMap data © OpenStreetMap contributors and available from https://www.openstreetmap.org",
             col = "#f1eee9",
             size = 0.75,
             position = c("left", "bottom"),
             fontfamily = "Arial Narrow")
```

```{r}
# Build the other layers

myPalette <-  "Reds"

vizWB <- tm_shape(leuWBDensities$polygons) +
  tm_fill(col = "level",
          palette = myPalette,
          legend.show = T,
          style = "cont") +
  tm_shape(leuGrid) +
  tm_borders(col = "#ffffff",
             lwd = 0.01) +
  tm_shape(leuHighwaysFilter) +
  tm_lines(col = "#737373",
            lwd = 0.01)

```

```{r}
# Put layers together

viz <- vizBase +
  vizWB
```

## Export

```{r}
# Export the map as an image to upload onto twitter

tmap_save(tm = viz,
          filename = here::here("2021/exports/Day27.png"),
          dpi = 450,
          width = 200,
          height = 200,
          units = "mm")

```

